### ISSUE TITLE
Question about the design

### ISSUE THREAD

**Issue by michaelmesser** [paf31/purescript-incremental-functions#6]
Very cool library. Why did you chose way 1 over way 2?
**1.** `(a, Chang a) -> (b, Change b)`

Pros:
- Allows more complex functions than way 2

Cons:
- Performance penalty when a `Change a -> Maybe (Change b)` function exists
  - The position of `a` must be kept in memory or recomputed to calculate the velocity of `b`
  - The position of `b` is recomputed every time there is a change in `a` even though the velocity of `b` may be all that is needed

**2.** `(a -> b, Change a -> Maybe (Change b))`

Pros:
- Simpler
- More efficient

Cons:
- Only allows simpler functions

**Comment by paf31** [comment]
The first option allows for composition of functions using ordinary function composition. That was the main motivation.

Note that you can also add a "no change" constructor to any change structure now, generically even, if you want to recover the usefulness of the `Maybe` you have there.

**Comment by michaelmesser** [comment]
Is there a difference in efficiency? It appears to me that using jet functions would lead to unneeded computations being performed in certain cases. Mainly, that `Jet a -> Jet b` requires `a` and recomputes `b` even if `Change a` can be directly mapped to a `Change b`. Hopefully my analysis is incorrect.

**Comment by paf31** [comment]
Depends how much laziness is implicit in the type of `b`. For my purposes this is not a problem, but you could wrap it all in a `Lazy` wrapper if necessary.
